### PR TITLE
Improved error handling

### PR DESCRIPTION
**Pull request by ddikman**
I found that using a key that had old or insufficient privileges to use the API ended up giving me a 403 API result but the error generated from the CLI was completely empty (there's no `err.message`).

This fix solves the problem by wrapping the error handling in a new function which ensures old functionality is intact in case the error isn't a response from the API with an error.

### CODE REVIEW

**Comment by roccomuso** [comment]
thanks.
PS. I'm also upgrading the dependencies. A full test would be appreciated before releasing on npm. Let me know thanks.

**Comment by ddikman** [comment]
Cheers and sorry for the out-of-nowhere PR :) I've got another edit where I added a "brief" mode as well to output the translation as is. I needed it for batch processing translations, I can put that into another PR if you like?

What kind of tests would you like? Could I build some kind of test suit to run through a couple of primary tests unless you have something lying around?

**Comment by roccomuso** [comment]
You're welcome to open PR :) btw I'm also looking for a maintainer. I'd be happy to add you as a maintainer.

Feel free to add and document the "brief" mode.

As a plus, basic unit testing will be fine. (using chai + mocha, or tape).

**Comment by ddikman** [comment]
Hey!
As for the tests, I'll try to set something up. Actually, I've never been a maintainer on anything. I might be up for it, what does it involve?

**Comment by roccomuso** [comment]
you'd be free to review or merge PR

**Comment by ddikman** [comment]
Sounds good to me :)

Though if you can spare the time, getting some comments on the code is always appreciated!

**Comment by roccomuso** [comment]
ok don't worry

**Comment by ddikman** [comment]
Hi!
I got some stuff ready for the brief output, additional tests and so. If you add me as a contributor I'll raise a PR from a new branch (instead of forking)

**Comment by roccomuso** [comment]
done

**Pull request merged**
