### PR TITLE
Bumped version

### PR DESCRIPTION
**Pull request by ddikman**
Upped version for NPM.

### CODE REVIEW

**Comment by roccomuso** [comment]
Tests are failing

**Comment by ddikman** [comment]
@roccomuso on the master branch? I have been working on another branch trying to get Travis-CI working but there are issues with moccha timing out. Can you elaborate?

**Comment by roccomuso** [comment]
I can't see a `.travis.yml`

**Comment by ddikman** [comment]
In a different branch:
https://github.com/roccomuso/gtranslate/tree/travis-builds

I've had issues getting the tests to work on the travis-ci container though, I'm kind of stuck. If you have any ideas I'd be very grateful:
https://travis-ci.org/roccomuso/gtranslate

**Comment by roccomuso** [comment]
do they pass locally?
Are you having issue with the stdout/cli? try do a mockup

**Comment by ddikman** [comment]
they do pass locally. I'm guessing it has to do with open handles on the streams for child_process. next step would be to try and produce locally using the same container travis-ci has but I don't have the time or machine to do it with now

**Pull request merged**
